server:
  port: 8082

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
    host: localhost
    port: 5672
    username: guest
    password: guest

aws:
  dynamodb:
    region: sa-east-1
    table: kitchen_orders
    statusIndex: gsi_status_createdAt

app:
  amqp:
    order-received-queue: kitchen.order.received

