server:
  port: 1

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
    host: localhost
    port: 5672
    username: guest
    password: guest


app:
  amqp:
    order-received-queue: kitchen.order.received