server:
  port: 8082

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    accessKey: dummy
    secretKey: dummy
    table: kitchen_orders
    statusIndex: gsi_status_createdAt

app:
  amqp:
    order-received-queue: kitchen.order.received



