server:
  port: 8082

spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
    host: localhost
    port: 5672
    username: guest
    password: guest

aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    accessKey: dummy
    secretKey: dummy
    table: kitchen_orders
    statusIndex: gsi_status_createdAt

app:
  amqp:
    order-received-queue: kitchen.order.received

